# Generated by Django 4.1.4 on 2023-01-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_rename_applicantincome_approvals_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='brain_stroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('hypertension', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('heart_disease', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('ever_married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('work_type', models.CharField(choices=[('Private', 'Private'), ('Self-employed', 'Self-employed'), ('Govt_job', 'Govt_job'), ('Never_worked', 'Never_worked'), ('children', 'children')], max_length=15)),
                ('Residence_type', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=15)),
                ('avg_glucose_level', models.IntegerField(default=0)),
                ('bmi', models.IntegerField(default=0)),
                ('smoking_status', models.CharField(choices=[('formerly smoked', 'formerly smoked'), ('never smoked', 'never smoked'), ('smokes', 'smokes')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='approvals',
        ),
    ]
